# Generated by Django 5.1.1 on 2024-10-17 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookkatalog', '0002_book_author_book_genre_book_published_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
    ]
