# Generated by Django 5.1.1 on 2024-10-17 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookkatalog', '0004_book_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='published_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
