# Generated by Django 5.1.1 on 2024-10-17 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookkatalog', '0005_alter_book_published_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='published_date',
        ),
    ]
