# Generated by Django 5.1.2 on 2024-10-29 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookkatalog', '0007_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.FileField(null=True, upload_to='book_img'),
        ),
    ]
